# Generated by Django 3.2.3 on 2021-07-15 20:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launcher',
            fields=[
                ('launcher_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('delay_time', models.BigIntegerField()),
                ('delay_puzzle_hash', models.TextField()),
                ('authentication_public_key', models.TextField()),
                ('singleton_tip', models.BinaryField()),
                ('singleton_tip_state', models.BinaryField()),
                ('p2_singleton_puzzle_hash', models.CharField(max_length=64)),
                ('points', models.BigIntegerField()),
                ('difficulty', models.BigIntegerField()),
                ('payout_instructions', models.TextField()),
                ('is_pool_member', models.BooleanField()),
            ],
            options={
                'db_table': 'farmer',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.BigIntegerField()),
                ('fee', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'payout',
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('size', models.BigIntegerField()),
            ],
            options={
                'db_table': 'space',
            },
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('launcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_partials', to='api.launcher')),
            ],
            options={
                'db_table': 'points',
            },
        ),
        migrations.CreateModel(
            name='PayoutAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_hash', models.CharField(max_length=64)),
                ('amount', models.BigIntegerField()),
                ('transaction', models.CharField(max_length=100, null=True)),
                ('confirmed_block_index', models.IntegerField(default=None, null=True)),
                ('launcher', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.launcher')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.payout')),
            ],
            options={
                'db_table': 'payout_address',
            },
        ),
        migrations.CreateModel(
            name='Partial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('launcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.launcher')),
            ],
            options={
                'db_table': 'partial',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('singleton', models.CharField(max_length=64)),
                ('timestamp', models.BigIntegerField()),
                ('confirmed_block_index', models.IntegerField()),
                ('puzzle_hash', models.CharField(max_length=64)),
                ('amount', models.BigIntegerField()),
                ('farmed_by', models.CharField(max_length=64, null=True)),
                ('payout', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.payout')),
            ],
            options={
                'db_table': 'block',
            },
        ),
    ]
