# Generated by Django 3.2.3 on 2021-07-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_partial_error'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Points',
        ),
    ]
