# Generated by Django 3.2.3 on 2021-07-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_block_farmed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='launcher',
            name='estimated_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
