# Generated by Django 3.2.6 on 2021-08-09 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_launcher_estimated_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='launcher',
            name='joined_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
