# Generated by Django 3.2.6 on 2021-08-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210809_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='launcher',
            name='points_pplns',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='launcher',
            name='share_pplns',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=21),
            preserve_default=False,
        ),
    ]
