# Generated by Django 3.2.6 on 2021-08-23 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210811_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain_height', models.BigIntegerField(default=0)),
                ('blockchain_space', models.BigIntegerField(default=0)),
                ('xch_current_price', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'globalinfo',
            },
        ),
        migrations.AlterField(
            model_name='block',
            name='payout',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='api.payout'),
        ),
    ]
