# Generated by Django 3.2.6 on 2021-08-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210823_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalinfo',
            name='blockchain_space',
            field=models.CharField(default='0', max_length=128),
        ),
    ]
