# Generated by Django 3.2.6 on 2021-08-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_globalinfo_blockchain_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='estimate_to_win',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='block',
            name='luck',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='block',
            name='pool_space',
            field=models.BigIntegerField(default=0),
        ),
    ]
