# Generated by Django 3.2.6 on 2021-08-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_partial_harvester_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='farmed_height',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='confirmed_block_index',
            field=models.BigIntegerField(),
        ),
    ]
