# Generated by Django 3.2.6 on 2021-09-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210829_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalinfo',
            name='blockchain_avg_block_time',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
