# Generated by Django 3.2.6 on 2021-09-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_globalinfo_blockchain_avg_block_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPartial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partial', models.JSONField(default=dict)),
                ('time_received', models.BigIntegerField()),
                ('points_received', models.IntegerField()),
            ],
            options={
                'db_table': 'pending_partial',
            },
        ),
    ]
