# Generated by Django 3.2.6 on 2021-09-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_pendingpartial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutaddress',
            name='pool_puzzle_hash',
            field=models.CharField(default='', max_length=64),
        ),
    ]
