# Generated by Django 3.2.6 on 2021-09-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_payoutaddress_pool_puzzle_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='referral',
            field=models.BigIntegerField(default=0),
        ),
    ]
