# Generated by Django 3.2.6 on 2021-10-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_globalinfo_wallets'),
    ]

    operations = [
        migrations.AddField(
            model_name='launcher',
            name='left_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
