# Generated by Django 3.2.6 on 2021-10-10 14:14

from datetime import timedelta
from django.db import migrations
from django.utils import timezone


def left_at_default(apps, schema_editor):
    Launcher = apps.get_model('api', 'Launcher')
    for launcher in Launcher.objects.filter(is_pool_member=False):
        launcher.left_at = timezone.now()
        launcher.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_launcher_left_at'),
    ]

    operations = [
        migrations.RunPython(left_at_default)
    ]
