# Generated by Django 3.2.6 on 2021-10-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20211010_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutaddress',
            name='fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payoutaddress',
            name='payout_round',
            field=models.IntegerField(default=1),
        ),
    ]
