# Generated by Django 3.2.6 on 2021-10-20 14:54

from django.db import migrations, models


def removedups(apps, schema_editor):
    Block = apps.get_model('api', 'Block')
    last = None
    for block in Block.objects.order_by('farmed_height'):
        if last == block.farmed_height:
            block.delete()
        last = block.farmed_height


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_block_absorb_fee'),
    ]

    operations = [
        migrations.RunPython(removedups),
        migrations.AlterField(
            model_name='block',
            name='farmed_height',
            field=models.BigIntegerField(unique=True),
        ),
    ]
