# Generated by Django 3.2.6 on 2021-11-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_block_farmed_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutaddress',
            name='tx_fee',
            field=models.BigIntegerField(default=0),
        ),
    ]
