# Generated by Django 3.2.6 on 2021-11-03 10:48

from django.db import migrations, models
import django.db.models.deletion
from chia.types.coin_spend import CoinSpend
from chia.pools.pool_puzzles import get_most_recent_singleton_coin_from_coin_spend


def copy_singleton(apps, schema_editor):
    Launcher = apps.get_model('api', 'Launcher')
    Singleton = apps.get_model('api', 'Singleton')

    for i in Launcher.objects.all():
        coinspend = CoinSpend.from_bytes(i.singleton_tip)
        singleton_coin = get_most_recent_singleton_coin_from_coin_spend(coinspend)

        singleton = Singleton()
        singleton.launcher = i
        singleton.singleton_name = singleton_coin.name().hex()
        singleton.singleton_tip = i.singleton_tip
        singleton.singleton_tip_state = i.singleton_tip_state
        singleton.save()



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_payoutaddress_tx_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singleton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_name', models.CharField(max_length=64)),
                ('singleton_tip', models.BinaryField()),
                ('singleton_tip_state', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('launcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.launcher')),
            ],
            options={
                'db_table': 'singleton',
            },
        ),
        migrations.RunPython(copy_singleton),
    ]
