# Generated by Django 3.2.6 on 2021-11-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_coinreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='launcher',
            name='fcm_token',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
