# Generated by Django 3.2.6 on 2021-11-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_launcher_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='launcher',
            name='qrcode_token',
            field=models.CharField(db_index=True, default=None, max_length=64, null=True),
        ),
    ]
