# Generated by Django 3.2.6 on 2021-12-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_launcher_qrcode_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='launcher',
            name='push_failed_partials_percent',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='launcher',
            name='push_missing_partials_hours',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='launcher',
            name='push_payment',
            field=models.BooleanField(default=False),
        ),
    ]
