# Generated by Django 3.2.6 on 2021-12-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20211218_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='launcher',
            name='push_block_farmed',
            field=models.BooleanField(default=True),
        ),
    ]
