# Generated by Django 3.2.6 on 2021-12-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20211220_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='xch_current_price',
            new_name='xch_price',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='xch_current_price',
            new_name='xch_price',
        ),
    ]
