# Generated by Django 3.2.6 on 2022-01-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20211222_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='launcher',
            name='custom_difficulty',
            field=models.CharField(choices=[('LOWEST', 'Lowest'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('HIGHEST', 'Highest')], default=None, help_text='Set a custom difficulty for the launcher to send less or more partials depending on preference', max_length=10, null=True, verbose_name='Custom Difficulty'),
        ),
        migrations.AddField(
            model_name='launcher',
            name='minimum_payout',
            field=models.BigIntegerField(default=None, help_text='Set a minimum value before sending out payout from rewards', null=True, verbose_name='Minimum Payout'),
        ),
    ]
