# Generated by Django 3.2.6 on 2022-02-11 13:06

from django.db import migrations


def created_at_time(apps, schema_editor):
    PayoutAddress = apps.get_model('api', 'PayoutAddress')
    for pa in PayoutAddress.objects.filter(transaction__created_at_time=None):
        if not pa.transaction:
            continue
        t = pa.transaction
        if not t.created_at_time:
            t.created_at_time = pa.payout.datetime
            t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_transaction_created_at_time'),
    ]

    operations = [
        migrations.RunPython(created_at_time),
    ]
