# Generated by Django 3.2.6 on 2022-02-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_transaction_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='partial',
            name='chia_version',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='partial',
            name='plot_id',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='partial',
            name='pool_host',
            field=models.CharField(default=None, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='partial',
            name='remote',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
    ]
