# Generated by Django 3.2.6 on 2022-02-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_pendingpartial_req_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingpartial',
            name='req_metadata',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
