# Generated by Django 3.2.6 on 2022-02-24 15:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_pendingpartial_req_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('launcher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.launcher')),
                ('size_drop', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PUSH', 'Push'), ('EMAIL', 'Email')], max_length=10), default=list, size=2)),
                ('size_drop_interval', models.IntegerField(default=None, null=True)),
                ('size_drop_percent', models.IntegerField(default=None, null=True)),
                ('size_drop_last_sent', models.DateTimeField(default=None, null=True)),
                ('failed_partials', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PUSH', 'Push'), ('EMAIL', 'Email')], max_length=10), default=list, size=2)),
                ('failed_partials_percent', models.IntegerField(default=None, null=True)),
                ('payment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PUSH', 'Push'), ('EMAIL', 'Email')], max_length=10), default=list, size=2)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.RemoveField(
            model_name='launcher',
            name='push_failed_partials_percent',
        ),
        migrations.RemoveField(
            model_name='launcher',
            name='push_payment',
        ),
    ]
