# Generated by Django 3.2.6 on 2022-03-09 10:45

from django.db import migrations, models


def copy_joined_at(apps, schema_editor):
    Launcher = apps.get_model('api', 'Launcher')
    for launcher in Launcher.objects.all():
        launcher.joined_last_at = launcher.joined_at
        launcher.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20220224_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='launcher',
            name='joined_last_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.RunPython(copy_joined_at),
    ]
