# Generated by Django 3.2.6 on 2022-03-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20220224_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='launcher',
            name='joined_last_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
