# Generated by Django 3.2.6 on 2022-03-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_launcher_left_last_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutaddress',
            name='fee_amount',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
