# Generated by Django 3.2.6 on 2022-03-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_payoutaddress_fee_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='launcher_effort',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='block',
            name='launcher_etw',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='launcher',
            name='current_etw',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='launcher',
            name='last_block_etw',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='launcher',
            name='last_block_timestamp',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['farmed_by_id'], name='farmed_by_idx'),
        ),
    ]
