# Generated by Django 3.2.6 on 2022-03-31 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20220326_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payoutaddress',
            name='payout_round',
        ),
    ]
