# Generated by Django 4.1 on 2022-08-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_remove_payoutaddress_payout_round'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Space',
        ),
    ]
