# Generated by Django 3.2.6 on 2021-09-21 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0016_payoutaddress_pool_puzzle_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.BigIntegerField(verbose_name='Total Income')),
                ('active', models.BooleanField(default=True)),
                ('active_date', models.DateTimeField()),
                ('launcher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.launcher')),
                ('referer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='api.launcher')),
            ],
        ),
    ]
